# Generated by Django 4.1.5 on 2023-02-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogpostCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='BlogpostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.blogpostcategorymodel')),
            ],
            options={
                'verbose_name': 'blogpost',
                'verbose_name_plural': 'blogposts',
                'db_table': 'blogpost',
                'ordering': ('-updated_at',),
            },
        ),
    ]
