# Generated by Django 4.1.5 on 2023-02-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_blogpostcategorymodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcategorymodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'verbose_name': 'blogpost', 'verbose_name_plural': 'blogposts'},
        ),
    ]
