# Generated by Django 4.1.5 on 2023-02-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_blogpostmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'ordering': ('-updated_at',), 'verbose_name': 'blogpost', 'verbose_name_plural': 'blogposts'},
        ),
    ]
